version: "3.7"
services:
  n8n-server:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    volumes:
      - ./.n8n:/root/.n8n
    ports:
      - "5678:5678"
    env_file:
      - ./n8n-setting.env

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: n8n
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
